apiVersion: apps/v1
kind: Deployment
metadata:
  name: atna-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atna
  template:
    metadata:
      labels:
        app: atna
    spec:
      containers:
        - name: atna
          image: eu.gcr.io/mscdevopscaauto/allthenews2:v1
          args: ["news", "http://nfa-service:8898", "weather", "http://wfa-service:8898","3", "10", "redis-service:6379"]
          ports:
          - containerPort: 8090	  
        # - name: atn-redis
        #   image: redis
        #   ports:
        #   - containerPort: 6379

