apiVersion: apps/v1
kind: Deployment
metadata:
  name: atna-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atna
  template:
    metadata:
      labels:
        app: atna
    spec:
      containers:
        - name: atna
          image: eu.gcr.io/mscdevopscaauto/allthenews2:v1
          args: ["news", "http://nfa-service:8888", "weather", "http://wfa-service:8888"]
          ports:
          - containerPort: 8080	  
        - name: atn-redis
          image: redis
          ports:
          - containerPort: 6379

