apiVersion: v1
kind: Service
metadata:
  name: nfa-service
  labels:
    name: nfa-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: nfa
  type: ClusterIP
