apiVersion: v1
kind: Service
metadata:
  name: wfa-service
  labels:
    name: wfa-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wfa
  type: ClusterIP
