apiVersion: apps/v1
kind: Deployment
metadata:
  name: atn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atn
  template:
    metadata:
      labels:
        app: atn
    spec:
      containers:
        - name: atn
          image: eu.gcr.io/eadesignca/allthenews1:v1
          args: ["news", "http://nf-service:8888", "weather", "http://wf-service:8888"]
          ports:
          - containerPort: 8080	  
        - name: atn-redis
          image: redis
          ports:
          - containerPort: 6379

