/*
 * The EADes News
 *
 * This is the first TUDTC MSc in DevOps EADes microservices example. 
 *
 * API version: 1.0.0
 * Contact: jvkitt@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"os"
	
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "allthenews/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	sw.Configure(os.Args[1:])
	
	log.Fatal(http.ListenAndServe(":8090", router))
}
