#!groovy

    def branch = env.GIT_BRANCH?.trim().split('/').last().toLowerCase()
    def siteUrl = params.SITE_URL?.trim()
    def buildNo = env.BUILD_ID

node {

    properties([disableConcurrentBuilds()])

    try {

        echo """Parameters:
            branch: '${branch}'
            siteUrl: '${siteUrl}'
            buildNo: '${buildNo}'
            workspace: '${WORKSPACE}'
        """

        // Triggers measure_response.sh, takes in site url
        def generateResponses = { url ->
            sh "chmod +x ${WORKSPACE}/measureResponses/measure_response.sh"
            sh "${WORKSPACE}/measureResponses/measure_response.sh ${url} ${buildNo}"
        }

        stage("Pull Source") {
            //trying to get the hash without checkout gets the hash set in previous build.
            def checkout = checkout scm
            env.COMMIT_HASH = checkout.GIT_COMMIT
            echo "Checkout done; Hash: '${env.COMMIT_HASH}'"
        }

        stage('Generate Responses'){
            // Call measure_response.sh to genereate response csv files.
            generateResponses("${siteUrl}")
        }
        
        stage('Draw plots'){
            plot csvFileName: 'plot-8e54e334-ab7b-4c9f-94f7-b9d8965723df.csv', 
                csvSeries: [[
                    file: "total_start.csv",
                    exclusionValues: '',
                    displayTableFlag: false,
                    inclusionFlag: 'OFF',
                    url: '']],
                group: 'Plot Group eadesignCA',
                title: 'Total starts',
                style: 'line',
                exclZero: false,
                keepRecords: false,
                logarithmic: false,
                numBuilds: '10',
                useDescr: false,
                yaxis: 'Responses',
                yaxisMaximum: '',
                yaxisMinimum: ''
            
            plot csvFileName: 'plot-8e54e334-ab7b-4c9f-93f6-g9e8965734eg.csv', 
                csvSeries: [[
                    file: "total_connect.csv",
                    exclusionValues: '',
                    displayTableFlag: false,
                    inclusionFlag: 'OFF',
                    url: '']],
                group: 'Plot Group eadesignCA',
                title: 'Total connects',
                style: 'line',
                exclZero: false,
                keepRecords: false,
                logarithmic: false,
                numBuilds: '10',
                useDescr: false,
                yaxis: 'Responses',
                yaxisMaximum: '',
                yaxisMinimum: ''
            
            plot csvFileName: 'plot-8e54e334-ab7b-4c9f-10f7-b9d8965745fh.csv', 
                csvSeries: [[
                    file: "total_time.csv",
                    exclusionValues: '',
                    displayTableFlag: false,
                    inclusionFlag: 'OFF',
                    url: '']],
                group: 'Plot Group eadesignCA',
                title: 'Total time',
                style: 'stackedBar',
                exclZero: false,
                keepRecords: false,
                logarithmic: false,
                numBuilds: '10',
                useDescr: false,
                yaxis: 'Responses',
                yaxisMaximum: '',
                yaxisMinimum: ''
        }

    } catch (e) {
        throw e
    } finally {
        // Recursively delete the current directory from the workspace
        //deleteDir()
        echo "Build done."
    }
}
